[build]
  command = "pip install -r requirements.txt && npm install"
  functions = "netlify/functions"
  publish = "public"

[context.production.environment]
  NETLIFY_IMPLICIT_FORM_SUBMISSIONS = "false"
