[build]
  functions = "netlify/functions"  # Keeps your Python functions directory
  publish = "public"              # Points to your public folder for static files

[context.production.environment]
  # Disable Netlify's default form notifications
  NETLIFY_IMPLICIT_FORM_SUBMISSIONS = "false"
